### PR TITLE
WIP: Update Integration

### PR DESCRIPTION
**Pull request by tylerauerbeck**
This updates Integration to use the appropriate applications and releases

### CODE REVIEW

**Comment by tylerauerbeck** [comment]
cc/ @jacobsee 

I think this is ready, but wanted to get another set of eyes on this

**Comment by jacobsee** [comment]
This makes me realize that I don't know why we have an ArgoCD CR both in here and in the runtime config repository, and how they interact with each other... Maybe I can get an explanation of the idea behind that at some point. Otherwise, nothing scary stands out - I think it's worth a try.

**Comment by tylerauerbeck** [comment]
@jacobsee They're in both places because this repository provides the base of it, while the one in our config repo provides the patches to it (i.e. our customizations, credentials, etc.)

**Comment by jacobsee** [comment]
@tylerauerbeck There is no chance that this one will be applied to the cluster _without_ patches and then patched quickly, is there? It will always be patched _before_ it ever hits the cluster? I ask because the options we're using on that operator are not idempotent...

**Pull request merged**
