### PR TITLE
Config split to separate LodeStar and Labs SRE Automation configurations apart

### PR DESCRIPTION
**Pull request by jfilipcz**
Splitted bootstrap into separate structures for LodeStar and Labs SRE Automation

### CODE REVIEW

**Comment by oybed** [comment]
Need to include changes to https://github.com/rht-labs/lodestar-deployment/blob/master/bootstrap/core/tools/restart-configurable-resources.yaml - i.e.: remove dispatcher + perhaps rename the job to avoid conflicts with the labs-sre-automation

**Comment by oybed** [comment]
Babylon references still exists, e.g.:
https://github.com/jfilipcz/lodestar-deployment/blob/split-out-labs-sre-automation/bootstrap/core/cluster/crd-reader.yaml#L27-L29

**Comment by jfilipcz** [comment]
I've pushed couple of updates - and I think this PR is ready for a review once again

**Comment by makirill** [comment]
I think https://github.com/rht-labs/lodestar-deployment/blob/master/.github/ISSUE_TEMPLATE/release.md should be updated to remove `babylon` references.

**Review by makirill — APPROVED** [review]

**Pull request merged**
